import { Open_Sans, Dancing_Script, Crimson_Text } from 'next/font/google'
import './globals.css'

const openSans = Open_Sans({ subsets: ['latin'], variable: '--font-open-sans' })
const dancingScript = Dancing_Script({ subsets: ['latin'], variable: '--font-dancing-script' })
const crimsonText = Crimson_Text({ subsets: ['latin'], variable: '--font-crimson-text', weight: '400' })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${openSans.variable} ${dancingScript.variable} ${crimsonText.variable}`}>
      <body>{children}</body>
    </html>
  )
}
